# Change these first
owner: hunger-status # Your GitHub organization or username, where this repository lives
repo:  hunger-status # The name of this repository

sites:
  - name: Hunger
    url: https://hunger.ai
  - name: Hunger Customer
    url: https://hunger.ai/g/index.html
  - name: Hunger Backend
    url: https://hunger.ai/api/v3/p/sys/time

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /hunger-status
  logoUrl: https://hunger.ai/favicon-32x32.png
  name: Hunger 夯客
  introTitle: "**Hunger 夯客**"
  introMessage: Service Status
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
